// <auto-generated />
namespace KBC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSomeIDsForURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSomeIDsForURL));
        
        string IMigrationMetadata.Id
        {
            get { return "201604231727258_Add Some IDs For URL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
